# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f2ee7cca8d39becde2ba439b4cbeb0ea982a8fcc0b1e0b33abb11219f8ecb7b55d166c7c96563334b9939ab23dbfaa62cea2dc43d01db0074c8e81f656cb560

test:
  secret_key_base: c9fea533400a427aa7a49fc40987a8073202f20900ac67e245bd882f16a33add38e27a9ce8915bf41ca2d8ebadc4ddff95b50ed9cf558dcb0909901d6991b987

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
